# config.yaml - 모든 설정을 하나의 파일에 통합
defaults: []  # 개별 컴포넌트 파일 참조 제거

# 데이터 설정
data:
  batch_size: 32
  num_workers: 0

# 모델 설정
model:
  model_name: gogamza/kobart-base-v2

# 옵티마이저 설정
optimizer:
  _target_: torch.optim.AdamW
  lr: 5e-05
  weight_decay: 0.1

# 콜백 설정
callbacks:
  early_stopping:
    _target_: pytorch_lightning.callbacks.EarlyStopping
    monitor: "val_loss"
    #monitor: "val_rouge-2"  # 변경
    patience: 15
    mode: "min"
    #mode: "max"           # ROUGE는 높을수록 좋음
    min_delta: 0.001
    verbose: True
  
  lr_monitor:
    _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: "epoch"
    log_momentum: False

  model_checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    save_top_k: 1
    monitor: "val_loss"
    mode: "min"
    #monitor: "val_rouge-2"
    #mode: "max"
    filename: best-{epoch:02d}-{val_loss:.3f}
    #filename: best-{epoch:02d}-{val_rouge-2:.3f}

# 트레이너 설정
trainer:
  _target_: pytorch_lightning.Trainer
  max_epochs: 15
  accelerator: "auto"
  num_sanity_val_steps: 2
  predict_with_generate: True
  #generation_max_length: 400

# tokenizer 설정
tokenizer:
  encoder_max_len1: 700
  encoder_max_len2: 170
  decoder_min_len: 10
  decoder_max_len: 170
  bos_token: "<s>"
  eos_token: "</s>"
  special_tokens:
    - "#Kristin#" 
    - "#CardNumber#" 
    - "#PersonName#" 
    - "#DateOfBirth#" 
    - "#SSN#" 
    - "#Person7#" 
    - "#PhoneNumber#" 
    - "#Email#" 
    - "#Person4#" 
    - "#PassportNumber#" 
    - "#Alex#" 
    - "#Person1#" 
    - "#Address#" 
    - "#Person6#" 
    - "#Name#" 
    - "#Person3#" 
    - "#Price#" 
    - "#CarNumber#" 
    - "#Bob#" 
    - "#Person5#" 
    - "#Liliana#" 
    - "#Person2#"
    - "#FlightNumber#"
  remove_tokens:
    - "<usr>"
    - "<s>"      # tokenizer.bos_token
    - "</s>"     # tokenizer.eos_token  
    - "<pad>"    # tokenizer.pad_token    

# custom 설정
custom:
  seed_num: 42     
  do_test: False
  do_checkpoint: False
  ckpt_path: "/data/ephemeral/home/work/python/upstageailab-nlp-summarization-nlp_3/logs/nlp-summarization/yzy3qjr9/checkpoints/best-epoch=00-val_loss=0.539.ckpt"