name: Sync Subtree
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
      - name: Update subtree
        run: |
          echo "Updating existing subtree..."
          # -v 옵션 제거, 디버그가 필요하면 -d 사용
          git subtree pull --prefix=duhwan/codes/gx-train https://github.com/korea202/gx-train.git main --squash
          
      - name: Push changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Changes detected, pushing..."
            git push origin main
          else
            echo "No changes to push"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
